#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Power Menu Script
# -----------------------------------------------------------------------------
# Descrption : This script provides a power menu using Rofi.
# location    : ~/.config/rofi/scripts/power
# Requires    : 'rofi', 'betterlockscreen', 'amixer'
# -----------------------------------------------------------------------------

# ───────────────────────────────────────────────────────────────
#                      Theme Settings
# ───────────────────────────────────────────────────────────────
dir="$HOME/.config/rofi/settings"

# ───────────────────────────────────────────────────────────────
#                         Menu Options
# ───────────────────────────────────────────────────────────────
shutdown='󰐥' # power-off (nf-mdi-power)
reboot=''   # restart (nf-mdi-restart)
lock='󰍁'     # lock (nf-mdi-lock)
suspend='󰤄'  # sleep (nf-mdi-sleep)
logout='󰍃'   # logout (nf-mdi-logout)

# ───────────────────────────────────────────────────────────────
#                           User Info
# ───────────────────────────────────────────────────────────────
username="󰣇 $(whoami)"

# Pick a random message
sendoff="POWER MENU"

# ───────────────────────────────────────────────────────────────
#                           Rofi Cmd
# ───────────────────────────────────────────────────────────────
rofi_cmd() {
	rofi -dmenu \
		-p "$username" \
		-mesg "$sendoff" \
		-theme ${dir}/powermenu.rasi
}

# ───────────────────────────────────────────────────────────────
#                       Run Rofi Menu
# ───────────────────────────────────────────────────────────────
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# ───────────────────────────────────────────────────────────────
#                        Command Exec
# ───────────────────────────────────────────────────────────────
run_cmd() {
	if [[ $1 == '--shutdown' ]]; then
		systemctl poweroff
	elif [[ $1 == '--reboot' ]]; then
		systemctl reboot
	elif [[ $1 == '--suspend' ]]; then
		amixer set Master mute
		systemctl suspend
	elif [[ $1 == '--logout' ]]; then
		pkill -KILL -u "$USER"
	fi
}

# ───────────────────────────────────────────────────────────────
#                           Execute Cmd
# ───────────────────────────────────────────────────────────────
chosen="$(run_rofi)"
case ${chosen} in
$shutdown)
	run_cmd --shutdown
	;;
$reboot)
	run_cmd --reboot
	;;
$lock)
	betterlockscreen -l blur
	;;
$suspend)
	run_cmd --suspend
	;;
$logout)
	run_cmd --logout
	;;
esac
